### ISSUE TITLE
BECCS modeling in Activity browser

### ISSUE THREAD

**Issue by Hd1004** [LCA-ActivityBrowser/activity-browser#1006]
Can someone please assist me in modeling BECCS in the Activity browser? In one process, I have methane as a product and the CO2 coming out of the process needs to be captured, stored, transported and then put underground to get the negative emissions from storing biogenic captured CO2. How do I incorporate it in the exchanges to include the expansion and get the negative emission intensity of the final fuel? Since it is not possible to use CO2 as a second product in the same process.

**Comment by Hd1004** [comment]
@cmutel @tmillross @zber @Joeytje50

**Comment by Zoophobus** [comment]
Hi @Hd1004

Is this discussion of use to you https://github.com/LCA-ActivityBrowser/activity-browser/discussions/996

**Comment by bsteubing** [comment]
Hi @Hd1004,

in your case you do not have a multifunctional process, but CO2 is a "waste product", i.e. _not_ an environmental, but a technosphere flow, which will then be captured, transported, and stored... so instead of including an enviromental flow for CO2 in the methane production, you need a negative input (i.e. an output) of CO2 as a technosphere flow. This means in the AB you first have to create a new process that "captures" the CO2 with a functional flow (product) of "CO2 captured" or something like this... check how wastes are modelled in the ecoinvent database. Hope this helps.

**Comment by Hd1004** [comment]
Hey @bsteubing  I did exactly the same thing and it worked. Thank you :)
