### ISSUE TITLE
Startup Project does not list same projects as the Projects tab

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#1074]
### Updating AB

- [X] Yes, I have [updated AB](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-ab) and still experience this issue

### What happened?

When trying to set a recent project as the "startup project" in settings, I notice that the list of projects there is different and does not include the projects I recently created. 

**List in Projects**
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/33026150/9737da79-2e5a-47f7-b91b-6a6e7de01d3e)

**List in Settings > Startup Project:**
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/33026150/2fe9ba3f-3e5d-4556-ac1e-97fe1cbb8266)

### Operating system

Windows 10

**Comment by Zoophobus** [comment]
I'll check this in the coming week/s, just a quick question, as I have a suspicion that this is due to the reading of the settings file, was this all in one session with the AB? If you close and reload the AB do the listed projects match?

**Comment by bsteubing** [comment]
It does not change if the AB is closed and reopened... there is simply a mismatch between the two and what the AB settings reads is not up to date, so there the call is probably wrong...

**Comment by marc-vdm** [comment]
I think this is caused by the following function:
https://github.com/LCA-ActivityBrowser/activity-browser/blob/5a953a0a23b488ae00630397b34fe9b43a3cafb6/activity_browser/ui/wizards/settings_wizard.py#L217

This function actually reads the Brightway dir (in your case `C:\Users\steub\OneDrive - Universiteit Leiden\Brightway3`) with our own function ([`self.bw_projects(path)`](https://github.com/LCA-ActivityBrowser/activity-browser/blob/5a953a0a23b488ae00630397b34fe9b43a3cafb6/activity_browser/ui/wizards/settings_wizard.py#L110)) while the dropdown in the projects tab reads the projects from Brightway:
https://github.com/LCA-ActivityBrowser/activity-browser/blob/5a953a0a23b488ae00630397b34fe9b43a3cafb6/activity_browser/ui/tables/projects.py#L21

What I propose is that we move [`self.bw_projects(path)`](https://github.com/LCA-ActivityBrowser/activity-browser/blob/5a953a0a23b488ae00630397b34fe9b43a3cafb6/activity_browser/ui/wizards/settings_wizard.py#L110) (perhaps under a different name) to the [ProjectController](https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/activity_browser/controllers/project.py) and then have the projects tab and the settings wizard read from there.

**Comment by mrvisscher** [comment]
If I understand your sollution correctly @marc-vdm your sollution would lead to the startup project list not updating when a new brightway dir is selected as the ProjectController is only updated after hitting save in the settings wizard. I'd suggest updating self.bw_projects(path) to read the projects from the db file in said path directly. Like so:


```python
def bw_projects(self, path: str):
        """ Read the bw_projects from the brightway2 environment provided by path"""
        db = SqliteDatabase(path +"/projects.db")
        cursor = db.execute_sql('SELECT "name" FROM "projectdataset"')
        return [ i[0] for i in cursor.fetchall()]
```

Also see the commit above
