### ISSUE TITLE
When to call the .process() method on a database? 

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#134]
To delete an activity completely (so that it is not used during LCA calculations anymore), we need to call database.process(). 
Issues with this:

- Currently the AB does not do this, so the deleted activites stay alive within, e.g. the technosphere matrix
- To call database.process() takes a couple of seconds, so it is probably not convenient to it after every activity deletion.

So: how to deal with this and when to call this?

**Comment by haasad** [comment]
- creating a `bw.LCA`-object calls `clean_databases`: [code](https://bitbucket.org/cmutel/brightway2-calc/src/c4bf5638053415e082fab63146c1177495824818/bw2calc/lca.py?at=default&fileviewer=file-view-default#lca.py-78)
- `database.process` is therefore called on any "dirty" database: [code](https://bitbucket.org/cmutel/brightway2-data/src/d7f6a7ecdc53190bbd7264e35e54e1366ea7aa3f/bw2data/meta.py?at=default&fileviewer=file-view-default#meta.py-114)
- database is set dirty when an activity is deleted: [code](https://bitbucket.org/cmutel/brightway2-data/src/d7f6a7ecdc53190bbd7264e35e54e1366ea7aa3f/bw2data/backends/peewee/proxies.py?at=default&fileviewer=file-view-default#proxies.py-69)
- Since we create a new [LCA-object](https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/activity_browser/app/bwutils/multilca.py#L30) for every calculation, `database.process` is always called before anything is caclulated

Only reason that I see to call `database.process` early would be to update the activity counter in the databases tab, ie a visual response that the activity was deleted. We could add a check like [here](https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/activity_browser/app/controller.py#L360) to call process on small databases, but ignore it for larger ones where it takes too long. But in general I think we're safe and brightway takes care of this automatically.

**Comment by bsteubing** [comment]
OK, then the issue I had was still related to a change that I made to a database previous to the current setup as you describe it. Perfect, issue can be closed.
