### ISSUE TITLE
Sankey diagram bugs

### ISSUE THREAD

**Issue by ricklupton** [LCA-ActivityBrowser/activity-browser#156]
Playing with the Sankey diagram tool I found a few errors that don't appear to cause major problems -- although I found it didn't always respond to clicks so perhaps fixing these would improve it.

Happy to make separate issues if you prefer. Using the development version, set up test as described in #152 

This seems to happen after the second level of expansion:
```
Traceback (most recent call last):
  File "/home/rick/anaconda3/envs/ab-dev/lib/python3.6/site-packages/activity_browser/app/ui/web/sankey/sankey.py", line 133, in link_selected
    target_key = int(link.split('-')[-2])
ValueError: invalid literal for int() with base 10: '__189_200_2'
```

This happens intermittently, possibly when clicking lots of times in a row:
```
js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
```

This happens when you click on the background because the `selectLink` event handler is called with null in that case (the intention being that you want to "cancel" an accumulated selection -- here just ignore it if null).
```
js: Uncaught TypeError: Cannot read property 'id' of null
```

**Comment by haasad** [comment]
Thanks for reporting these bugs!

The first one was related to links with several segments, ie. expanding only worked if the last segment was clicked, otherwise the code didn't handle the segement ids properly. Fixed in a66127858c88b9b00effb25dd145853b76201c76

I can reproduce the second bug by clicking very fast repeatedly. It doesn't appear to have any negative effects however, so I'll leave this for now as it is.

Third one has been bothering me for a while, I fixed it now in e1897b0c0d7f2c41758903fdd58862a8ae87d394
