### ISSUE TITLE
Add the 'location' in the activities of the in the 'project' tab

### ISSUE THREAD

**Issue by rafaellaurenti** [LCA-ActivityBrowser/activity-browser#163]
Hi guys,

Is it possible to add the location of each of the activities of ecoinvent? The location of some are displayed but not for all activities. It is specially hard to work without knowing the location when there are many activities with the same name (e.g. electricity production,...) but for a different location. I have to blindly double click in one activity to find out the respective country in the 'activity tab'.

Many thanks!

Rafael Laurenti
EPFL

![image](https://user-images.githubusercontent.com/39736183/40664873-2d800184-635c-11e8-891a-e32620592c29.png)

**Comment by haasad** [comment]
Hi Rafael,

thanks for the input. I'm quite sure that this is related to #80 and #84, where some attributes are not displayed properly after the table is reordered. This should already be fixed in the newest development version. I recommend you do the following:
```
conda uninstall activity-browser
conda install activity-browser-dev
```
This will install the most up-to-date version of the AB. Please let me know if this fixes the issue for you.

Cheers,
Adrian

**Comment by rafaellaurenti** [comment]
Hi Adrian,

Thank you for your prompt reply and instructions! It worked well!

Best regards,
Rafael
