### ISSUE TITLE
Issues with simply getting Brighway2 to run with ecoinvent datasets

### ISSUE THREAD

**Issue by wzbernstein** [LCA-ActivityBrowser/activity-browser#171]
Currently, we are trying to map manufacturing process models that carry analytical expressions in a MathML representation to ecoSpold and to run the generated files in Brightway2 to conduct some LCAs.   We are running into some persistent errors using Brightway (even with Ecoinvent files) and thought someone here might provide some helpful guidance/insight.

We have been using EcoEditor and the Ecoinvent 3.4 database as a reference source. We are able to save the datasets in the ecoSpold2 format following the Brightway documentation + examples.   We tried to import the datasets, but when we executed the command: “apply_strategies”, got an error at the "create_composite_code" strategy with "KeyError: 'flow'".  Strangely, we found 2 datasets that work with the same exact procedure (acetanilide production, GLO, 2010 - 2010.spold being one of them).

Any  ideas?

**Comment by haasad** [comment]
Welcome the the AB. First of all, this is probably not the ideal place to look for support for basic brightway problems. The issues in this repository are used to discuss matters that concern the activity browser. Brightway and its core packages are developed on bitbucket, see the [brightway homepage](https://brightwaylca.org/) for more details. There is also a [brightway tag](https://stackoverflow.com/questions/tagged/brightway) on stackoverflow, where you can reach more people for support. I'll close this issue since it's off-topic for the AB, but feel free to ask follow-up questions here.

Regarding your problem:
- Were you able to import ecoinvent 3.4 in brightway and calculate some basic LCIA results?
- The error that you get probably means that your own ecospold files miss a reference product. Brightway creates a code from the name of the activity and the reference product (see [docs](https://docs.brightwaylca.org/intro.html#activity-hashes))
- Where does your `acetanilide production` dataset come from? I can't find a corresponding global (`GLO`) dataset in ecoinvent 3.4.
