### ISSUE TITLE
Report bug option

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#25]
This is currently not working and too prominent. Perhaps we could have it report issues to this repository, but in the MenuBar under "Help".

**Comment by haasad** [comment]
I created a github account `ActivityBrowser`, which can report issues from the AB. See #49. I would actually like to keep it in a prominent place. I think this could be a useful feature, but only if people really report the bugs. However I changed the color from red back to black to make the button a bit less annoying.

**Comment by haasad** [comment]
> What do you mean by "I created a github account ActivityBrowser"?

The "report bug" needs an own account for this to work, see #46, #47, #48 etc

> Can we make a compromise in terms of location? I think top left is not ideal as the first thing users see is "report bug". What a great software :-) If you want to keep it in the Menubar, then lets have it after the "Project" buttons and probably some more stuff to come. And perhaps we should add an entry under "Help" as well.

Completely agree. What about the debug window? These two are somehow connected in my mind.

**Comment by haasad** [comment]
Found the reason why it doesn't work anymore :-)

> Hello ActivityBrowser,
>
>We noticed that a valid OAuth access token of yours was committed to a public GitHub repository. Publicly disclosing a valid access token would allow other people to interact with GitHub on your behalf, potentially altering data, your contact information, and billing data.
>
>As a precautionary measure, we have revoked the OAuth token. A new token will need to be generated in order to continue using OAuth to authenticate to GitHub. Here are a couple of steps you can do to ensure your account security has not been compromised:
>
>* Review any unauthorized OAuth applications, and remove any you don’t recognize: https://help.github.com/articles/keeping-your-ssh-keys-and-application-access-tokens-safe/#reviewing-your-authorized-applications-oauth
>* Review you security log to ensure that no other malicious activity has occured: https://help.github.com/articles/reviewing-your-security-log/
>
>The commit in question is at https://github.com/LCA-ActivityBrowser/activity-browser
>
>Please feel free to contact us at https://github.com/contact if you have any questions or concerns.
>
>Thanks,
>GitHub.com

**Comment by haasad** [comment]
In an ideal case, people would just sign up for github and raise the issue here, right? Maybe we should really go with your suggestion of adding an option in the help menu and inform the users about the possibility of raising the issue here, ie get rid of the bug button completely.

The other option would be to keep the bug-feature and somehow obfuscate the token. The advantage of the token (as opposed to a password) is that i allows fine-grained access control, ie. no login, only access via api, only access to repos but not to account etc. But the possibility of someone abusing the token can't be ruled out. The token could eg. be used to spam other repos with issues etc.

**Comment by haasad** [comment]
Fixed with #65. See eg #67 and #64
