### ISSUE TITLE
GUI: Windows forget their open/closed state

### ISSUE THREAD

**Issue by levonamatuni** [LCA-ActivityBrowser/activity-browser#270]
Products/Techn. inputs/Bio. Dlows/Downstr. Cons. windows forget their checkmark of being visible/invisible when switching from one activity to the other. For instance, canning through techno. inputs of various activities (while other windows are invisible) become difficult as with every new activity all the other windows appear all over again obstructing the list of techn. inputs. 
Could be helpful.
Thanks!

**Comment by dgdekoning** [comment]
This seems to be an excellent use for application settings: allowing the user to set in advance which tables in the activity tab should be visible or not.

Though: even when for example the biosphere table is always closed, there should still be an indicator that this is because of user settings, not because the table is empty.

**Comment by Zoophobus** [comment]
@levonamatuni well we have had a few discussions on this and the final conclusion was to retain the current settings. While some use was found for your suggestions the main takeaway was that it potentially more of a marginal use case and that having the standard settings is generally more practical for the average user. Feel free to protest and reopen this, however I'll close this issue for now
