### ISSUE TITLE
[Remark] Activity pannel no longer opens if activity has no 'reference product' (since Version 2.3.3)

### ISSUE THREAD

**Issue by ntropy-esa** [LCA-ActivityBrowser/activity-browser#280]
Hello Daniel,

Just to let you know that since 2.3.3, if I have a database with custom activities (non generated via the AB, but rather own script) and that these activities don't have by default a 'reference product' (i.e. an exchange of type 'production' with input = output = tuple of itself); then double-clicking on its name no longer opens the activity explorer/editor.

But all other features seem to work: performing LCA calculations, opening them in the graph explorer,...

Not a real bug/issue as it just forces me to define reference products systematically.
Thanks for the work you're doing.

**Comment by dgdekoning** [comment]
Hey @ntropy-esa, thanks for bringing this up!

Ever since I added the `activity.production( )` [check](https://github.com/LCA-ActivityBrowser/activity-browser/blob/6edb7982f6ef27bd7569c8b2464fe71cb7589a6f/activity_browser/app/ui/tabs/activity.py#L34-L35) to stop users from opening biosphere activities I was wondering when people would start having this problem.

If you have the time and energy we would welcome a more robust solution! Possibly by looking into the activity for the type? Or maybe there are specific fields by which we can reliably separate biosphere and technosphere activities?
