### ISSUE TITLE
adding biosphere flows to activities

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#294]
dragging from the inventory table into an editable activity should add an exchange regardless of whether it is dragged correctly to either biosphere or technosphere flows. The activity will simply have a new exchange, which can be shown in the right table upon updating the activity. This also does not need the check for "emission / natural resource " etc. in a settings file.

**Comment by dgdekoning** [comment]
I agree that it improves usability to just drag and drop new exchanges into either of the two tables and let the application sort it out.

What I did note is that the code used to determine where to place the exchange isn't actually anywhere in the table code but instead in the controller.
In order to remove the check for 'type' we would have to alter that method and also feed it the database name the dragged activity is from.
