### ISSUE TITLE
biosphere datasets are not opened in tab

### ISSUE THREAD

**Issue by cardosan** [LCA-ActivityBrowser/activity-browser#3]
HI guys,
when I open a database in a project, while I can open activities in the separate tab this is not possible with biosphere datasets. Is this the expected behaviour.
I think would be convenient to be able also to open such a type e.g. to explore the activities that uses a certain biosphere flow downstream.

**Comment by haasad** [comment]
I'd say this is expected behaviour. When you open a bioshphere activity as a dictionary in brightway it look something like this:
```
(('biosphere3', 'ac98d2a4-4985-49f9-b4e2-fc896ef145b6'),
 {'categories': ('air', 'non-urban air or from high stacks'),
  'code': 'ac98d2a4-4985-49f9-b4e2-fc896ef145b6',
  'database': 'biosphere3',
  'exchanges': [],
  'name': 'Uranium-234',
  'type': 'emission',
  'unit': 'kilo Becquerel'})
``` 
Name, categories and unit are already displayed in the activities table in the AB. There is no additional info to be displayed in a seperate tab.

On the other hand I agree that it would be very convenient to be able to filter activities by biosphere flows. I would propose to integrate this into an advanced search feature, where you can display all activities that have a certain biosphere flows. I think this would be more user-friendly than opening a new tab for every biosphere flow that you want to explore.
