### ISSUE TITLE
Importing / migrating databases

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#324]
When importing databases, one issue is that the name of the database may prevent correct importing. For example if my database is called "cut-off36" but the database that I am trying to import links against "cutoff36", it is the simple lacking "-", which prevents correct importing.

While this is the simple case, the other case is version migration, e.g. from ecoinvent 3.5 to 3.6. This can be done using matching and the correspondance file of ecoinvent and it should be explored how such a migration can be facilitated at the level of the AB, probably making use of an underlying bw-migrations library or something similar.

**Comment by StpdFox** [comment]
For the first issue we could write a regular expression that filters certain characters and suggests possible databases. 

The second issue could be a bit more complicated since version migration always has a few odds and ends. It could result in a simple match & move, but it could also be a big parser and almost a seperate program. If there are certain database versions we want to migrate we could look at the posibility but it'll be quite a task to implement it for all versions

**Comment by StpdFox** [comment]
Opened a seperate issue for the first issue mentioned. https://github.com/LCA-ActivityBrowser/activity-browser/issues/573

**Comment by marc-vdm** [comment]
This was solved with database relinking and the current importer asking how to link database dependencies right?

If so, please close.
