### ISSUE TITLE
Import option for excel data files

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#329]
While there are many possible standards, I suggest to rely on this standard.

relying on this template: 
https://nbviewer.jupyter.org/urls/bitbucket.org/cmutel/brightway2/raw/default/notebooks/Parameters%20-%20Excel%20import.ipynb

@cmutel is that still what you would recommend?

**Comment by dgdekoning** [comment]
Related to #257.

**Comment by lugasraka** [comment]
Hello, does that mean one should create the inventory in an excel sheet, load it in Python (via Brightway), and only after that it can be imported through Activity Browser?

**Comment by dgdekoning** [comment]
@lugasraka, Somewhat like that yes.
As soon as you load the data in through Brightway (in python) it becomes available in the Activity Browser.

The difficulty with implementing this is due to the fact that we also want to import (and activate) different kinds of parameters through the same excel file.

At some point in the future I would like to add a button to the Activity Browser that allows users to import the excel document directly instead of going through Brightway.

**Comment by lugasraka** [comment]
Ah yes @dgdekoning thanks. So I need to set_up a new database using excel importer and populate it so it can be called through AB.
