### ISSUE TITLE
Issue switching from one project to another

### ISSUE THREAD

**Issue by romainsacchi** [LCA-ActivityBrowser/activity-browser#373]
I am experiencing issues switching from one project to another, on the welcome page.
The error thrown is the following:

![image](https://user-images.githubusercontent.com/22473067/75147900-ad748d00-56fe-11ea-8567-f3141ad825e1.png)

The app does not totally crash, but the content of the project is not shown.

**Comment by dgdekoning** [comment]
I think I've come across something like this before, is it possible that at some point you imported data through brightway and used `create_new_biosphere` method? I think that is the only method that [quietly creates a 'file' database](https://bitbucket.org/cmutel/brightway2-io/src/c2e61ee68fcadca57d5dd3eb2492e96f060252be/bw2io/importers/base_lci.py#lines-299:314) instead of defaulting to sqlite.

The easiest 'fix' on your end would be to remove the database through brightway. Probably not something you want to do.

Brightway2 code says we can iterate through a singlefile database, so some slight changes to the AB should fix the issue.

**Comment by dgdekoning** [comment]
Together with the databases table there are 4 instances of `len` being called on `bw.Database`.

**Comment by romainsacchi** [comment]
That could indeed be the issue. Thanks for the answer. I'll see in the meanwhile if I can do without the additional biosphere db.

**Comment by romainsacchi** [comment]
Yes, I can reproduce the error in brighway2.
This would throw an error:
`len(bw.Database("additional_biosphere"))`

**Comment by dgdekoning** [comment]
A short solution would be to use `sum(1 for _ in bw.Database("additional_biosphere"))` where it counts all the activities.

Going through the code I've noticed a few other possible issues (`bw.Database` is being pumped directly into a pandas DataFrame in the `MetaDataStore` class) but I'm unsure if these require changes or if the `__iter__` implementation in the `SingleFileDatabase` allows all of that to work correctly.

**Comment by dgdekoning** [comment]
Building a development version with the fix included now. Thanks for reporting this @romainsacchi and please don't hesitate to bring up any other issues you come across!
