### ISSUE TITLE
[bug] AB becomes larger than screen resolution with too large dropdowns

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#381]
The AB widens further than screen resolution when dropdown names that are too long in the x contributions tab. See figure for view. I tried and cannot resize the AB to become smaller.

A potential fix would be to limit the amount of characters shown in the dropdown field, perhaps we can keep the full names available in the dropdown menu itself?

![Screenshot AB](https://user-images.githubusercontent.com/34626062/75874155-151a8e80-5e09-11ea-859e-e7ec71456a47.png)

edit: I`m also not allowed to resize the screen smaller when I collapse the left (database) field.

**Comment by mwskelton** [comment]
I have seen similar behavior immediately after calculating an LCA. When the LCA results tab is shown, if the drawn figure is too wide for the available window space, the AB becomes wider than the screen and cannot be resized. Additionally, once the window is unmaxmized (in order to drag it sideways to view the rest of the window), it no longer seems to want to maximize (see screenshot below). If it is useful, this is on a system running Linux Mint 20 in MATE desktop environment. No obvious error output in the terminal from which AB is running.
![ab-window-bug](https://user-images.githubusercontent.com/90456871/133634221-9c3d1d0d-9182-420a-b2fc-3b52ec485498.png)

**Comment by marc-vdm** [comment]
Thanks for sharing! We are currently revising the graphs entirely, which should also resolve this issue.
