### ISSUE TITLE
SingleFileDatabase breaks database listing in AB

### ISSUE THREAD

**Issue by Loisel** [LCA-ActivityBrowser/activity-browser#384]
I have a `brightway2.SingleFileDatabase` object in my project. As soon as I open AB and select the project, I obtain
```
Traceback (most recent call last):
  File "~/miniconda3/envs/actbr/lib/python3.6/site-packages/activity_browser/app/ui/tables/table.py", line 57, in wrapper
    sync(self, *args, **kwargs)
  File "~/miniconda3/envs/actbr/lib/python3.6/site-packages/activity_browser/app/ui/tables/inventory.py", line 85, in sync
    row, 3, ABTableItem(str(len(bw.Database(name))), db_name=name)
TypeError: object of type 'SingleFileDatabase' has no len()
```
As a result, only one database is displayed in the corresponding listing in AB:
![Screenshot from 2020-03-09 12-05-57](https://user-images.githubusercontent.com/6737625/76207611-67d7ba00-61fe-11ea-997a-acbd4a330ccd.png)

Using AB 2.2.5., conda 4.8.2, on Ubuntu 18.10.

**Comment by dgdekoning** [comment]
Hey @Loisel! This seems similar to #373, which has been resolved in the recent development versions.

In order to make use of SingleFileDatabases you will need to use the latest `activity-browser-dev` version [as described here](https://github.com/LCA-ActivityBrowser/activity-browser#development-version).

**Comment by Loisel** [comment]
Ah nice, on dev the issue is resolved. Thank you your (fast) help!
