### ISSUE TITLE
Scenario based LCA - Presamples: add a warning if duplicates in presamples indices due to flawed scenario excel sheet

### ISSUE THREAD

**Issue by CHarpprecht** [LCA-ActivityBrowser/activity-browser#430]
Hi,
I think it would be helpful to warn the user when importing LCA scenarios from an excel sheet in case there are duplicates in the presamples indices. This can avoid importing flawed scenario data, which might be overlooked by the user when generating the excel sheets but could be easily pointed at, when importing the scenario data.

**Comment by dgdekoning** [comment]
I definitely agree with this sentiment and will look into adding console print statements for debugging.

**Comment by dgdekoning** [comment]
The current 'fix' I have for this is to add a `Found and cleared X duplicate exchanges` in the debug console. Would that be enough @CHarpprecht?

Possible other additions I can make is a one-time popup warning about duplicate exchanges (one-time because otherwise I feel it will start to annoy the user).
Adding the information on which exchanges are dropped is also possible, but I feel this can quickly get out of hand if put in the debug console (100+ lines of duplicate exchanges...)

Can you think of other improvements I can include?

**Comment by CHarpprecht** [comment]
Hi @dgdekoning, 
thank you for your fix! 
I tried to test it, but unfortunately ran into another problem, see issue [#432](https://github.com/LCA-ActivityBrowser/activity-browser/issues/432) . 
So I can't really say a lot ;) I think a one-time popup warning also sounds good to draw attention to this tricky situation, since I assume, that people do not check the debug console regularly, unless something is not working. But I can't really judge right now given the error ;)

**Comment by CHarpprecht** [comment]
Thank you, @dgdekoning! 
It is working now for me :) It is dropping the duplicates at the top and only uses the exchange on the bottom. 

I thought it might be helpful to mention in the console e.g. the first 3 dropped exchanges of a potentially much longer list of dropped exchanges. 
This can help the user to identify and eliminate the problem but limits the length of additional lines in the console.
