### ISSUE TITLE
Cannot change parameters in a project

### ISSUE THREAD

**Issue by MaximeAgez** [LCA-ActivityBrowser/activity-browser#441]
Hello. 
I am reporting a bug for a colleague that is not on Github. I do not have first hand information on the bug. I at least have screenshots of the error and a bit of the context in which the bug occurred.

Description of the bug:
Parameters (project, database and activity) in the "parameters/definition" tab cannot be modified anymore, neither renamed or changing the value. The SQL query fails triggering an error. This happens at the project level.

My colleague told me they did not go into brightway (no operation with the source code) and only stayed on the activity-browser.

I think this is a rather major bug as it forced my colleague to delete the project and restart it from scratch. We could not pinpoint the potential action(s) that caused the bug unfortunately.

View in AB:
Note that Pyrolyse_(réacteur) was an activity created in another database than the one shown on the screenshot. The screenshot was taken when we tried modifying a parameter in a blank database. Deleting the activity Pyrolyse_(réacteur) from the database still triggers an error at the project level.
![image](https://user-images.githubusercontent.com/24285636/93633490-0ff3ea00-f9bd-11ea-966b-ff461639a8ef.png)

View in conda:
![image](https://user-images.githubusercontent.com/24285636/93633469-07031880-f9bd-11ea-9563-eb535b06559f.png)

**Comment by dgdekoning** [comment]
Hello @MaximeAgez,

Parameters failing like that is a massive issue. Can you say which version of the AB you and your colleague are using?
A fix for ActivityParameters not being deleted when the related Activity was removed (#426) was added in version 2.6. This fix won't correct already existing problems but it should stop them from occurring again.

It looks like your issue is the opposite: An activity parameter was deleted some time ago, but is still in use by either other activity parameters or the parameterized exchanges of the activity.

I'm definitely looking into this as soon as possible.

**Comment by MaximeAgez** [comment]
Hi @dgdekoning,

the version used is 2.6.0.1
