### ISSUE TITLE
Importing excel files in AB

### ISSUE THREAD

**Issue by schvanes** [LCA-ActivityBrowser/activity-browser#458]
Hi everyone, 

I have an issue regarding the import of excel databases. So before I started to use the activity browser, I already used the Brightway jupyter notebook. There I imported my excel files without any problems. Now I would like to use the activity browser. First of all, suddenly it is not possible anymore to import the same excel files I already used. It seems like some exchanges could not be linked (but before they could - and I imported the same ecoinvent database 3.6). Basically I do not understand what I would need to change in order to make activity browser happy. In order to solve my problem, I thought I could just go back to brightway jupyter notebook and import the excel files there, but somehow since I downloaded the activity browser, it is just not possible to open the jupyter notebook again. The error message I get is the following:
![image](https://user-images.githubusercontent.com/70581538/95431577-ac226880-094d-11eb-94d4-69585942a8dd.png)

I also tried to copy the suggested link in the error message, but still the jupyter notebook does not open. 

Can someone help me? That would be really nice!

I am looking forward to your reply and I especially hope, that I could properly explain my issue! Thanks. 

Cheers,
Vanessa

**Comment by schvanes** [comment]
Thank you, Daniel, for your quick help. I am still not able to import excel files. 

What I really do not understand is that the activity browser recognizes my project from Brightway and accepts the databases of the excel files (I can look at these activities, perform LCAs and so on). But when I would like to add a new project with e.g. adapted databases in the excel files, activity browser always tells me that these exchanges cannot be linked. 

Many thanks again. 

Cheers, 
Vanessa

**Comment by dgdekoning** [comment]
Hey @schvanes,

What I found out over the course of the week is that the excel import (and export) is still very picky about correctly linking exchanges. There are some things I need to add to the pull-request on top of the small change I already put in there.

A small list of these is:
- having an `activity` field in your activity will break the import in half, causing it to fail.
- having a `product` column (instead of `reference product`) will cause the exchanges to fail to link, somehow.
- importing an excel database that is linked to multiple other databases is still a bit finicky, and will need more tweaking to make sure that the exchanges link well. The changes proposed in the pull-request won't quite fix the problem there.

**Comment by schvanes** [comment]
Hey @dgdekoning 

Many thanks for your help again! 👍 

According to your list, the problem is that I have several databases which are linked to each other. As a first solution for my project, I will import them in Brightway and use the activity browser in the next step.  

All the best
Vanessa
