### ISSUE TITLE
Unable to open activity-broswer

### ISSUE THREAD

**Issue by ar-ali** [LCA-ActivityBrowser/activity-browser#480]
Hi,

I have installed the activity-browser using the instructions provided under <> code. However, I unable to open the activity browser after final installation. I have attached the screenshot of the error I get in my command prompt. I would really appreciate some help. Thank you.

Best,
Ali
![ab-error](https://user-images.githubusercontent.com/75308720/100730880-ee56ac00-33ca-11eb-854d-c391bdd024f5.JPG)

**Comment by dgdekoning** [comment]
Hey @ar-ali. Sorry to hear you're having this issue.

Basically, this is caused by a difference between python 3.7 and 3.8 (see [here](https://github.com/brightway-lca/brightway2-data/issues/68) and [here](https://github.com/LCA-ActivityBrowser/activity-browser/issues/388) for a more in-depth explanation).

If possible, my suggestion is to use python 3.8 instead of 3.7.

You can either try and upgrade the python version in your current `ab` environment:
```bash
conda upgrade -n ab -c conda-forge -c cmutel -c bsteubing -c haasad -c pascallesage python=3.8
```
or remove the environment with `conda remove -n ab --all` and recreate it with:
```bash
conda create -n ab -c conda-forge -c cmutel -c bsteubing -c haasad -c pascallesage "activity-browser>2.4" python=3.8
```

**Comment by ar-ali** [comment]
Dear @dgdekoning 

Thank you for your prompt response. The issue is resolved now. 

Best,
Ali
