### ISSUE TITLE
`#NUM!` values in `amount` and `loc` columns in XLSX are imported as the number 36 by the Activity Browser.

### ISSUE THREAD

**Issue by mixib** [LCA-ActivityBrowser/activity-browser#514]
Consider an XLSX file in the brightway import format, with the value `#NUM!` for some of the exchanges `amount` and `loc` columns.

![bug01_XLinput](https://user-images.githubusercontent.com/53601545/106488509-112d3b80-64b4-11eb-9742-423b68b32097.jpg)

Following the way in which amounts are calculated based on formulas containing parameters on import, I expected that the `amount` would be calculated as a mean value based on the uncertainty data. Instead it shows as the number 36 on the Activity Browser. Only when modifying the uncertainty fields exchange by exchange there is a prompt to update the `amount` to match with the mean.

![bug01_prompt](https://user-images.githubusercontent.com/53601545/106486962-7ed86800-64b2-11eb-896a-2aeab01111d1.jpg)

According to brightway's [documentation](https://2.docs.brightway.dev/intro.html#uncertainty-type), the `uncertainty type` fields are defined in the package [`stats_arrays`](https://stats-arrays.readthedocs.io/en/latest/). When using a triangular distribution (ID-5), it is expected that when the mode is not provided, the `loc` value becomes the average between the `minimum` and the `maximum` values. Then, I expected `#NUM!` in the `loc` field to be replaced by the calculated `loc`. Instead it shows as the number 36 on the Activity Browser.

![bug01_loc36](https://user-images.githubusercontent.com/53601545/106487060-97e11900-64b2-11eb-851a-1e0a434bc88d.jpg)

Is this normal behaviour? If so, is it documented that the `LCA results` tab reports on calculations based on the `amount` and not on the uncertainty fields?

**Comment by dgdekoning** [comment]
This... is pretty bizarre. Can you forward the information about how distributions make up for missing data?

So this #NUM! field is always translated to 36 during the import? That shouldn't be normal behaviour.
But otherwise it kind of is normal behaviour that the AB (and I think brightway) make use of the `amount` field by default and only look into the `uncertainty` fields when performing Monte Carlo analysis or similar.

**Comment by mixib** [comment]
>Can you forward the information about how distributions make up for missing data?

I didn't look into the code of the [stats_array](https://stats-arrays.readthedocs.io/en/latest/) package, but the table under 'Mapping parameter array columns to uncertainty distributions' provides an overview of the required and optional parameters. If the optional parameters aren't specified, then these parameters are calculated by default. See an excerpt of the table below.

![bug01_defaultCalculations](https://user-images.githubusercontent.com/53601545/106922407-56987580-670d-11eb-9962-2a4e1b36f73e.jpg)


>So this #NUM! field is always translated to 36 during the import? 

Using the database in my input file, it does. The database in the file has about 17 processes, so something I could do is verifying with a single process database. 

>But otherwise it kind of is normal behaviour that the AB (and I think brightway) make use of the amount field by default and only look into the uncertainty fields when performing Monte Carlo analysis or similar.

It makes sense.

**Comment by Zoophobus** [comment]
Hi Mixib,

so I've been going through this and am finding that brightway (version 2) is dealing with these errors slightly differently now. When I've introduced them what occurs is that brightway excludes the field containing the error, which is personally not ideal, however it is safe and does allow us to throw some warnings/errors. So while it may not be perfect we don't really lose any functionality as a result of it.

From my perspective I feel like it might be better for us to throw an error rather than to try and adapt to these errors/missing values. The reason being is that it's only going to be yourself (the user) who knows what should be happening with your exchanges, while having the AB being clever could hide these errors from you and make it harder to trace back to the original problem.

**Comment by marc-vdm** [comment]
Closing as resolved in #921
