### ISSUE TITLE
Download the Sankey diagram with high quality.

### ISSUE THREAD

**Issue by eketju** [LCA-ActivityBrowser/activity-browser#516]
Hello,

I would like to know if it is possible to download the Sankey diagrams (results) with good quality. This option will be really helpful to import those fantastic images into a ppt or doc document.
Thanks in advance for your support!

<img width="550" alt="Sankey" src="https://user-images.githubusercontent.com/67191839/106920926-cad21980-670b-11eb-83e5-3d96af05f79b.PNG">

**Comment by dgdekoning** [comment]
Related to #477.

Also, for more fine-tuning of diagrams to download: #511, #459, #438

**Comment by dgdekoning** [comment]
As for actual feedback:

The big issue with why we cannot download the Sankey diagram right now is that the diagram itself is generated by a Javascript library, which is then displayed within the AB by means of a tiny HTML page.
So in order to export the diagram, we need to get a trigger into the HTML page through a button outside the page.

Quick thoughts on how to implement this:
- Have an export button that asks the user for a name+location of the exported file.
- Add html/javascript code that allows for exporting of the graph to a file when given a path.
- package the filepath from step one into a signal and link it to the javascript code itself (similar to how the graph updates are done)
