### ISSUE TITLE
[bug] database excel export and re-import fails

### ISSUE THREAD

**Issue by BenPortner** [LCA-ActivityBrowser/activity-browser#549]
Dear activity-browser developers,

I realized that exporting a database to excel and re-importing it fails under certain circumstances. The error occurs if activities cannot be uniquely identified. The exported excel contains columns `name | amount | database | location | unit | type`. However, some ecoinvent activities cannot be uniquely identified by these fields and need the `reference product` additionally (e.g. `platinum group metal, extraction and refinery operations` from APOS 3.7). Could you add this information to the exported excel file to enable smooth re-import?

All the best.
Ben

**Comment by dgdekoning** [comment]
The AB excel exporter already explicitly includes the `reference product` field precisely because of this uniqueness issue. Is it going wrong when exporting APOS 3.7?

It is actually possible to add the information back into the excel file manually (an option if the export is of manageable size...).

**Comment by BenPortner** [comment]
@dgdekoning thanks for the hint. Updating to version 2.6.3 did the trick. My bad! 🙏
