### ISSUE TITLE
Suggested feature: list of interventions for which characterization factors are lacking

### ISSUE THREAD

**Issue by mixib** [LCA-ActivityBrowser/activity-browser#584]
Currently, when performing a calculation using an LCA setup, the LCA results tab shows an inventory in the first tab and the LCA results of the impact categories in the LCA setup. 
![image](https://user-images.githubusercontent.com/53601545/115581437-4c2b5800-a2c8-11eb-844c-cc8aa1245153.png)

The feature I propose is a filter in the inventory tab, similar to the already existing "biosphere flows" and "technosphere flows" to distinguish between the biosphere flows that have characterization factors in the selected impact categories and the ones who lack characterization factors.
![image](https://user-images.githubusercontent.com/53601545/115581323-31f17a00-a2c8-11eb-8807-0121bd7f27ec.png)

As further reference, CMLCA produces a list per alternative when choosing from a drop-down list containing the considered impact categories.
![image](https://user-images.githubusercontent.com/53601545/115582445-4124f780-a2c9-11eb-856a-80a110c86e8e.png)

**Comment by Zoophobus** [comment]
This issue has been addressed, however instead of the radio buttons suggested we have opted for a drop-down menu as in the presented case in CMLCA. The reason being to allow users to specify all flows, as well as having a reliable approach to automate the switching of the options after switching away and back to the biosphere flows. This approach allows us to maintain a coherent appearance within the GUI
