### ISSUE TITLE
bw2data.backends.peewee.schema.ActivityDataset

### ISSUE THREAD

**Issue by maw-cu** [LCA-ActivityBrowser/activity-browser#611]
Dears,

Out of nothing I cannot open the activity browser user interface anymore.

I tried updating it but still problem persists.

I am getting this error message:

bw2data.backends.peewee.schema.ActivityDatasetDoesNotExist: <Model: ActivityDataset> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."data", "t1"."code", "t1"."database", "t1"."location", "t1"."name", "t1"."product", "t1"."type" FROM "activitydataset" AS "t1" WHERE (("t1"."database" = ?) AND ("t1"."code" = ?)) ORDER BY Random() LIMIT ? OFFSET ?
Params: ['apos31', '7bfb07b2fe2e408f46bef81de587f84b', 1, 0]

My programming skills & knowledge are basic so I apologise for any inconvenience this message might cause.

Mohammad

**Comment by maw-cu** [comment]
I am facing this problem most probably because the SingleOutputEcospold2Importer failed to import ecoinvent into ActivityBrowser. I consumed a lot of memory & the computer crashed.

Is there no way back???

I tried to install the activity browser in a new environment & I got the same error!!!!

**Comment by maw-cu** [comment]
I have installed activity-browser dev & I can finally run the user interface.

Can this be a permanent solution?

**Comment by cmutel** [comment]
@maw-cu Please provide the complete error traceback (if in doubt, more is better than less), so we can see where exactly the problem is coming from.

**Comment by maw-cu** [comment]
There is no error message anymore! 🤷

**Comment by tdebonnet** [comment]
Hello, 
I have the same kind of error because I wanted to change the ecoinvent version and I am not able to relink my dataset with a more recent version of ecoinvent. I tried something and at the end I wanted to delete the old version but it deleted all activities but not the database which is now empty. 
So, now I cannot relink my databases with the new version of ecoinvent and I cannot see my databases linked with the old version : 
"
Broken exchange: <Model: ActivityDataset> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."data", "t1"."code", "t1"."database", "t1"."location", "t1"."name", "t1"."product", "t1"."type" FROM "activitydataset" AS "t1" WHERE (("t1"."database" = ?) AND ("t1"."code" = ?)) ORDER BY Random() LIMIT ? OFFSET ?
Params: ['ei33', '7762ef4fea820e0450d70b3261baa111', 1, 0], removing.
Exchange was deleted, continue.
+showing tab: Activity Details"

Do you know how to deal with these issues please? 
Tristan
