### ISSUE TITLE
I am having trouble in launching Activity-browser

### ISSUE THREAD

**Issue by Varun-Gowda-Palahalli-Ramesh** [LCA-ActivityBrowser/activity-browser#656]
![Screenshot from 2021-10-03 19-25-15](https://user-images.githubusercontent.com/85590445/135764822-799fb268-9270-4948-9382-61d42210d2fc.png)

Can you help me resolve this.

**Comment by StpdFox** [comment]
Hello! This seems to be an issue in bw2calc, have you tried updating it through Conda?
I'll try to replicate your issue in order to fix it. In the meantime, could you try installing the Dev version of the AB? 
This might fix the problem

**Comment by flixwar** [comment]
Hey, I've got the same issue. Installing the Dev version of the AB doesn't run, too.

**Comment by Varun-Gowda-Palahalli-Ramesh** [comment]
Dev version shows the same error for me too.

**Comment by StpdFox** [comment]
Hey there. 
The problem was a version update of bw2calc,  which we didnt restrict in our recipe. So when a new dev version hits, it got installed during an update/fresh install of the AB. So some functions have changed in the new version, breaking the current Ab. 
Luckally there's an easy fix which will be deployed on the dev. 
You can also apply it to your own environment by downgrading the bw2calc version : 
In your conda environment type `conda update bw2calc=1.8.0` 
And everything should work again.

**Comment by flixwar** [comment]
Great it works! Thanks for the support!

**Comment by romainsacchi** [comment]
I was having the same issue, and downgrading `bw2calc` to 1.8.0 made it disappear. However, still not possible for me to launch the AB. I'm using Python 3.9.7 and AB 2.4.0 and it is on a brand new conda environment.
![image](https://user-images.githubusercontent.com/22473067/135856764-b8f527e4-5e70-4170-9ee6-dd46048f2768.png)

**Comment by romainsacchi** [comment]
Hmm, wait a second, that's strange: following the conda instructions, it went on to pick v.2.2.4 from the haasad channel. I can see that the newest version is in fact 2.6.3. Can it be because the haasad channel has priority over the bsteubing channel in my conda configuration?

**Comment by StpdFox** [comment]
This is a new error for me. I think it's the case that haasad's channel has a priority yes, you could try switching priority. 
Conda does describe it in their documentation : [conda channel priorities](https://stackoverflow.com/questions/48547046/resetting-conda-channel-priorities)

**Comment by romainsacchi** [comment]
OK, I solved my issue. I think AB 2.6.3 has an upper boundary for the allowed Python version (which I think is 3.8). Having 3.9, conda would downgrade AB to a version that did not have such limit (2.2.4). I tried again with Python 3.8, and conda could install 2.6.3.
Since bw2io does not work well with Python 3.7 (because of some change in the default pickle protocol used), it means that really, the only viable option (at least for me) is to use Python 3.8, not more, not less.

**Comment by Varun-Gowda-Palahalli-Ramesh** [comment]
@StpdFox Thanks!! I was able to launch AB

**Comment by StpdFox** [comment]
> OK, I solved my issue. I think AB 2.6.3 has an upper boundary for the allowed Python version (which I think is 3.8). Having 3.9, conda would downgrade AB to a version that did not have such limit (2.2.4). I tried again with Python 3.8, and conda could install 2.6.3. Since bw2io does not work well with Python 3.7 (because of some change in the default pickle protocol used), it means that really, the only viable option (at least for me) is to use Python 3.8, not more, not less.

Yeah, we've mostly upgraded to 3.8 in the dev version aswell. The pickle protocol was a big reaason.



> @StpdFox Thanks!! I was able to launch AB

Great! If there's anything else you might need help on , or just general ideas on the AB , don't hesitate to drop by :)
