### ISSUE TITLE
Could not import a excel file as a database

### ISSUE THREAD

**Issue by Bubu25** [LCA-ActivityBrowser/activity-browser#686]
Hi,

I use the 2.6.3 version of activity-browser. 
By doing some import export tests of a database  with activity-browser, I got the following issue:
   here the steps:
     1) I exported to excel format a database named "Elegancy" present in the activity-browser  and which depends on
        ecoinvent3.7.1 cut off and biosphere3 .
     2) I deleted the database Elegancy in the activity-browser
     3) I tried to re-import the excel file got  with the activity-browser 

But  I got the following error  : "Could not link exchanges, here are 10 examples"
Below, you can see the screenshot that I got:
![ImportexceleError](https://user-images.githubusercontent.com/52828092/141296300-a577b962-8b77-46dc-b7e1-6c436b6a179f.jpg)

In order to understand the origin of the issue, I tried the following tests:
  - I tried the same tests (export, import) with  ecoinvent3.7.1 cutoff database and there was no issue, it worked
  - I tried to import the excel fil "Elegancy" through a  jupyter notebook script, here a part of this code:
                
                      from activity_browser.bwutils import importers
                      elegancy_fg = importers.ABExcelImporter(r"Elegancy.xlsx")
                      bw.projects.set_current("Elegancy")
                      
                      elegancy_fg.apply_strategies()
                      elegancy_fg.match_database("ecoinvent 3.7.1 cutoff", fields=('name','unit','location', 'reference product'))
                      elegancy_fg.statistics(),
                      elegancy_fg.write_excel(only_unlinked=True)
                      elegancy_fg.write_database()

    by doing that, It worked, I could  re-import the database Elegancy

Hope  my explanation is clear?
Thanks for you help

**Comment by marc-vdm** [comment]
Thanks for sharing your issue! Your issue seems to be linked to #614.
If you would have the time, could you try to [update the activity browser](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-activity-browser) and try to import the database again -perhaps under a different name, so you don't need to delete your current version- and then let us know is the issue persists? With that info we can look further into making sure other's don't have the same issue later.

In general, if you encounter issues, it is best to try and update the activity browser and see if the issue still exists.

In case you run into the issue again with the updated version, could you share your database and activity browser version number (just to be sure your update was successful)? That way we could see if we can replicate the issue. If your database contains confidential information, you could change numbers or names to your liking, though it would be preferred if you could leave the 'faulty' processes the same for us to have the exact same output.

**Comment by Bubu25** [comment]
Hi,

So my issue was solved :)!
Actually, there was a "little" mistake in my Elegancy.xlsx file which one was created at the beginning by running a jupyter notebook (see  a part of this code in my previous message). 
In this file for a given activity and a given exchange, the categories field should have been empty and was not.

Thank you for your help

**Comment by Bubu25** [comment]
Sorry not the categories field, but the location field should have been empty!

**Comment by marc-vdm** [comment]
>So my issue was solved :)!
Sorry, it's not entirely clear if that was solved by you fixing the file or updating the AB, could you clarify that please?

**Comment by Bubu25** [comment]
by fixing the file,

**Comment by marc-vdm** [comment]
Alright thanks for the info!
