### ISSUE TITLE
Use CSV or TXT for Scenario Difference files

### ISSUE THREAD

**Issue by romainsacchi** [LCA-ActivityBrowser/activity-browser#693]
Excel limitations in terms of size (1048576 rows) for scenario difference files, will quickly become an issue in the future, as more changes are brought to the database.
A switch to CSV or TXT files would be wise I think.

**Comment by marc-vdm** [comment]
Sounds like a good addition (though I'm not sure how many people encounter this issue haha). IIRC, the importer makes the sheet a Pandas DF anyway, so that should not be an issue to import from CSV.

This may perhaps be combined with bugfixing the excel importer (#614) as this has been an ongoing issue for a while now.

**Comment by marc-vdm** [comment]
@bsteubing 
I think doing this is not very difficult. We can split up [`import_from_excel`](https://github.com/LCA-ActivityBrowser/activity-browser/blob/b53caf9f6a417396e2e840bfe84ef4957c1011af/activity_browser/bwutils/superstructure/excel.py#L50) in [excel.py](https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/activity_browser/bwutils/superstructure/excel.py) into 2 parts: 2 functions for reading a pandas df (something like `import_from_excel` and `import_from_csv` with `pd.read_csv()` and one function that is called by one for the first 2 for the rest of the code in the original `import_from_excel`.

I think the most sensible location to add this is excel.py, however, then the file-name doesn't make sense anymore. What should we call it? importer.py?

**Comment by marc-vdm** [comment]
merged

**Comment by romainsacchi** [comment]
Hi @marc-vdm ,

what is the status on importing CSVs instead of Excel files?

**Comment by marc-vdm** [comment]
We dropped this after realizing the original reason we needed this was a problem with Premise outputting too many lines rather than a 'real' need.

Why are you asking? I'm sure that with the old code we could implement this without very much hassle. Though if we do re-open, I'd prefer some input with regards to CSV formatting (as many activity and environmental interventions contain `,` in their names).

**Comment by romainsacchi** [comment]
Actually, we start having this problem again, and it is not because of useless rows.
When creating scenarios using IMAGE, because it has 26 regions, and because premise "regionalizes" quite a bit of datasets now, the number of unique exchanges with amounts different than the original database increases dramatically now, especially when considering vehicle fleets.

The downside of using CSVs is that CSVs are not compressed and store pure strings, which takes a lot of memory on disk. For example, a 2 million rows CSV would take half a GB, so not really a solution.

But, if you could make so that when importing an Excel file, it forms a dataframe by concatenating all the sheets contained in the workbook, I could work. Meaning, on my end, if the SDF has over 1M rows, I'd split over several sheets of the same Excel file.

And on your end, this could do the trick (whether there is one or several sheets, I think)
`df = pd.concat(pd.read_excel(workbook_url, sheet_name=None), ignore_index=True)`

What do you think?

**Comment by marc-vdm** [comment]
I see, then let's broaden this issue toward running a lot of scenario data, independent of format.

CSV indeed is not ideal due to the size of data on disk, but other our current loader is slow anyway (#807 for an issue on profiling that code, you could help by timing a few things with scenarios you consider representative if your workload if you have the time). If scenarios files with millions of exchanges are going to become the norm (which I expect them to), we may need to look at more future proof solutions than excel.

There's a tradeoff between 3 things: 1 size on disk, 2 loading speed and 3 human-readability.

We may want to start having a look at binaries instead of human-readable formats for such files. We stopped with presamples because it's not human readable -and nobody seemed to be using it-, but human-readability is arguably not really relevant anymore with the current ~500k lines and now more lines scenarios have. Presamples was just a Numpy pickle and it's small on-disk and takes mere seconds to load instead of the minutes you need to wait now. Though we could (should) also explore other formats if we're re-implementing anyway, presamples was not perfect.

I think we should discuss this in a larger circle for more permanent solutions. @bsteubing what are your thoughts on this?
