### ISSUE TITLE
Show open databases as tabs

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#715]
I'd like to suggest of instead of having databases open 'one at a time' to move the entire [activities widget](https://github.com/LCA-ActivityBrowser/activity-browser/blob/043845aed913e0ec20b0f18c8e0d6d3a5dd32950/activity_browser/layouts/tabs/project_manager.py#L166) (including the search) into tabs, one for each open database. This solves 2 issues:
1. Search can be preserved for different databases
2. Users can easily switch between open databases that they are working on or are viewing

We could move the name of the db to the tab, also providing more space for the search bars.
It would also be nice to have a right click option on the 'database tab' to close the database, or just a close button, removing it from the tab bar again.
![image](https://user-images.githubusercontent.com/34626062/154107528-e09c6686-02e0-4ed3-85d4-a4b48d133e3c.png)

Half related: #632

**Comment by bsteubing** [comment]
One of the reasons I originally created the `MetaDataStore` is that it takes a couple of seconds to load the metadata for all activities in a database. So when switching to another one and then coming back to the original one, it can - instead of reading it from the database again - read it from the `MetaDataStore`, which is faster. Now your idea of storing the metadata in separate tabs, basically provides the same as this data is now stored (in memory) across the tabs. So in a way it does not require the `MetaDataStore `for this specific application anymore. I have not thought further than this, so it could well be that keeping the `MetaDataStore `is a good idea still since it also provides the metadata in the LCA Results/Inventory tab etc.

**Comment by marc-vdm** [comment]
Personally, I like keeping it, it is indeed also useful in LCA results. Additionally, I was also using it for the new modular LCA implementation, as is indeed also useful there for the metadata.
