### ISSUE TITLE
Montecarlo simulation & sensitvity analysis

### ISSUE THREAD

**Issue by maw-cu** [LCA-ActivityBrowser/activity-browser#777]
I am really disappointed how some features have turned out to be unstable. In my case, I have life cycle inventories that are based on 10-15 parameters with different uncertainty distributions. When I run a Montecarlo simulation that is solely based on the uncertainty of these parameters, I get the following:
1. For the same reference flow: different output curves depending on whether I run the Montecarlo simulation with 1 reference flow at a time or more. 
2. Strange sensitivity analysis results that make me doubt whether the uncertainties of all parameters were implemented in the Montecarlo simulation

**Comment by cmutel** [comment]
@maw-cu Seconding the request for more information! It's hard to diagnose anything without more specifics.

Re: #1, why would you expect them to stay the output curves to stay the same if you change the number of values needed for each iteration? The random number generator normally wouldn't work that way.

Re: #2, I was surprised by this because I didn't see any explicit [mention of paramterization in the GSA paper](https://onlinelibrary.wiley.com/doi/full/10.1111/jiec.13194), but the code [clearly includes parameters](https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/activity_browser/bwutils/sensitivity_analysis.py#L339), so I don't know why this wouldn't work.

**Comment by marc-vdm** [comment]
Closing as stale
