### ISSUE TITLE
Plugin code development

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#819]
Hi @Pan6ora, I see you're developing some code related to plugins. Great to see you're working with AB! In case you're interested in -at some point- adding your code to the main AB fork, could you explain a bit more about your plans? I'm working on some code at the moment that we will probably move into a plugin once completed. so it may be useful to collaborate/coordinate if you're working on functionality to add plugins to AB.

Please let me know! In case you'd rather not discuss publicly, I could also continue contact over email.
[fork for reference](https://github.com/Pan6ora/activity-browser/tree/plugin-manager)

Best,

M

**Comment by Pan6ora** [comment]
Hi @marc-vdm, 

Indeed I have been working on a plug-in system for AB in the past months for an internship in a research laboratory.

I was planning to start a merge request, to have a discussion with other people to see how to improve it and maybe to add it one day to AB.

The reason I haven't done it sooner is because I wanted to share a working stuff and not only a scratch.

Sadly I didn't had the time to do it before the end of my internship. Now I'm on holidays until September where I will continue working on it for the laboratory. 

Some infos that could help you before that :

- The branch plugin-manager on my fork contains a working version of my work
- A plugin template and infos on how to use it can be found at [this url](https://gricad-gitlab.univ-grenoble-alpes.fr/green-scop/ab-plugins/template) (the ReSICLED plugin mentioned should not work as I didn't had the time to upload the working version). This is maybe the best start to understand how things work
- I have a bit of documentation that I will try to push if I get my hands on my pc before September
- The plugin principle is to load python code "on-the-go" during AB execution that add tabs containing the plugin stuff. I didn't had too much code to AB so things may be understandable as is

Hoping this will help you and looking forward to work with you,

Rémy

**Comment by marc-vdm** [comment]
Hi Rémy,

Thanks for the explanation, this sounds like a really cool project. We (AB developers) are for sure interested in your work! Once you're back from holiday, would you be interested in telling us more/demonstrating your work? This may give some 'real world' application to your internship outside of just the lab you interned at. No hurries though, first enjoy your holiday!

**Comment by Pan6ora** [comment]
Hello Marc,

Back to work I am ready to tell you more about this plugin system !
Maybe we could organize a call so that I could show you my work and have a real discussion about it ? Send me an email if you (and other developers) are interested.

Best,
Rémy

**Comment by Zoophobus** [comment]
Hi @Pan6ora, given that you have published the plugin making this publicly available I will close this issue as it no longer seems valid. @marc-vdm is this okay for you too?
