### ISSUE TITLE
Linux - settings cannot navigate to default location

### ISSUE THREAD

**Issue by jphbutler64** [LCA-ActivityBrowser/activity-browser#871]
The default location for storing data on linux (Ubuntu)  (AB 2.6.9) is `~/.local/share/Brightway3`.
But `.local` is a hidden directory and thus does not appear in the file navigator that opens up with `Files > Settings > Browse`.

Workaround: change the contents of `~/.local/share/ActivityBrowser/ABsettings.json`  manually everytime there is a need to go to another directory.

Use case: switching to setup of other users in order to help them with their models.

**Comment by Zoophobus** [comment]
Hi I'm not sure that I get exactly what your issue is here, could you provide a bit more of a description of the situations where you do this? As I understand your issue you want to be able to navigate back to "hidden" directories, for keeping your databases and brightway environment, is that correct?

**Comment by Zoophobus** [comment]
Hi @jphbutler64 I guess @haasad has solved this, should I then close this issue? Or are there other points to this issue that need more attention?

**Comment by jphbutler64** [comment]
Hi @zoophobus, Thanks. The purpose is to visit colleagues' working directories, and revert back to mine when I have finished helping them. In my current version, nothing happens with a right-click. I will reinstall and test in the coming days.

A broader issue is that I do not feel that ~/.local/share is the right place for storing the projects; /var/brightway2 would feel more natural when working as a team.

I am also under the impression that no more than one person can work on a project at a time. If that is the case, then that is fine, but it would then be nice if we could also chown -R the directory to another user from the menus and show who has access to the various objects. If there are no such constraints, then group permissions on the files need to be reviewed / documented.

**Comment by haasad** [comment]
![image](https://user-images.githubusercontent.com/11636405/201171994-b4acc14f-6558-480c-8cf6-e70d7142f586.png)
```
lsb_release -d
Description:	Ubuntu 20.04.5 LTS
```
```
conda list -n ab activity-browser
# packages in environment at /home/adrian/miniconda3/envs/ab:
#
# Name                    Version                   Build  Channel
activity-browser          2.6.9                      py_0    bsteubing
```

**Comment by haasad** [comment]
Regarding the location of the brightway projects:
- you would probably have to raise that issue at https://github.com/brightway-lca/brightway2-data, this is not controlled by the ActivityBrowser
- brightway2 uses [appdirs](https://github.com/ActiveState/appdirs) for a cross-platform way to determine where the projects are stored
  - on linux this is `~/.local/share/`, because it needs to be user writable
  -  conda/brightway/acitivy-browser can all be installed without sudo privileges, and `/var/` is not user writable
- you can use the `BRIGHTWAY2_DIR` environment variable to change the path where brightway projects are stored
- to my knowledge brightway projects are not intended to be worked on by several people simultaneously, but I could be wrong

Managing user permissions (chown-ing directories etc.) is completely out of scope for the ActivityBrowser in my opinion.

**Comment by haasad** [comment]
#607 and #696 are potentially related to this issue

**Comment by Zoophobus** [comment]
As @haasad has written part of the access and rights access you would like are out of the scope of the AB, we can't change these and (probably) shouldn't. I would personally prefer to keep the activity-browser installable without the need for super user priviliges, as this will help users in institutions where sudo priviliges aren't provided. I would also echo the comment on editing permissions and ownership, this is for me command line functionalities (desktop too) and shouldn't be duplicated in the AB. 

In a point on the BRIGHTWAY2_DIR variable we have edited it's usage to allow users to store different values in the settings file. While this may not satisfy you I hope you can understand our position. I hope that we have at least addressed your immediate issue.

I will try and close this issue within the week if no further reasons to keep this alive come up. Of course feel free to reopen this if needed!
