### ISSUE TITLE
Finalize migration to conda-forge

### ISSUE THREAD

**Issue by haasad** [LCA-ActivityBrowser/activity-browser#892]
Thanks to the incredible work by @m-rossi the activity-browser and all of the missing dependencies (including all of the brightway ecosystem) are now available from `conda-forge` :partying_face: 

See https://github.com/brightway-lca/brightway2/issues/47 for some details

The AB has been accepted this morning (see https://github.com/conda-forge/staged-recipes/pull/21445)  and this now simplifies the installations process significantly:
```
conda create -n test --dry-run -c conda-forge activity-browser --json | jq .success
true
```
This means we can get rid of all the `cmutel` and `bsteubing` channel config and simply install from conda-forge.

Things that still need to be done:
* Add required people as recipe maintainers in https://github.com/conda-forge/activity-browser-feedstock
  * I guess @bsteubing + @marc-vdm + @Zoophobus 
* Update the installation instructions
* Update the github actions @haasad 
* Discuss on the release cycle and how to deal with the split between stable and dev
  * In my opinion the clean solution would be to just have the stable version on conda-forge and keep the dev version in the `besteubing` channel (we can't release a new package on conda-forge for every push to master)
  * However in that case the release frequency of the stable version would have to be sped up

**Comment by marc-vdm** [comment]
This is really awesome!
I think we need to have a proper look at our release system anyway.

What I think we need is a way to release smaller bugfixes/minor features to both `stable` and `dev` at the same time, while only testing 'larger' features on the `dev` that can, after we're happy, also be merged into `stable`. 

@haasad Would you be able to help us figure out a system for this?

I'm thinking, if we base all our new things from the a `stable` branch (e.g. a new branch, or just master), and then merge them into either `stable` or `dev` (e.g. master or a new branch called `development_release`/`beta` or something).
If I understand correctly, this would work for new features that don't depend on other new features, we could just merge them into both `stable` and `dev`.
Then, if we'd have new features that depend on eachother, they'd need to be built on the same branch (based on `stable`), and eventually merge into the `dev` branch, and when the features work well (on their own branch), merge them into `stable` too.

Would this make sense? Please think along, I'm hoping you have more experience with this!

**Comment by m-rossi** [comment]
> * Add required people as recipe maintainers in https://github.com/conda-forge/activity-browser-feedstock
>   * I guess @bsteubing + @marc-vdm + @Zoophobus

As @haasad already did, you can open an issue in https://github.com/conda-forge/activity-browser-feedstock and choose _Bot commands_ or use [this link](https://github.com/conda-forge/activity-browser-feedstock/issues/new?assignees=&labels=&template=2-bot-commands.yml) and use `@conda-forge-admin, please add user @USERNAME` as title. Then @haasad or me just have to merge the request.

> * Update the installation instructions

I opened PRs for most of the repositories in the brightway-ecosystem. I will also add one here.

> * Discuss on the release cycle and how to deal with the split between stable and dev
>   * In my opinion the clean solution would be to just have the stable version on conda-forge and keep the dev version in the `besteubing` channel (we can't release a new package on conda-forge for every push to master)
>   * However in that case the release frequency of the stable version would have to be sped up

In general conda-forge is meant for stable package versions. Although there are ways to add [Pre-release builds](https://conda-forge.org/docs/maintainer/knowledge_base.html#pre-release-builds) we should not _flood_ with packages for each new commit in the master branch. Furthermore updating pre-release versions is a more manual process instead of the highly automated process for updating stable versions using the conda-forge bot. However if you release pre-releases (like beta- or rc-versions) on github/pypi we could setup the feedstock to also package those versions. Ping me if you want to setup that. I can help there.

**Comment by m-rossi** [comment]
Digging through the documentation of the ecosystem I also noticed the optional `pypardiso` requirement for `bw2calc` which is not listed in the pypi. I will try to sort it out in https://github.com/conda-forge/bw2calc-feedstock/pull/1.

**Comment by haasad** [comment]
@m-rossi The situation with the solver library is a bit more convoluted, until now there were some workarounds in place because bw2calc and the activity-browser both used `noarch` builds. With the conda-forge infrastructure and architecture-specific builds it should be possible to simplify this a lot.

Workarounds:
- https://anaconda.org/cmutel/brightway2_nosolver/
- https://anaconda.org/bsteubing/activity-browser-arm

Ideally there should also be and requirement for [scikit-umfpack](https://anaconda.org/conda-forge/scikit-umfpack) for `osx` and `arm64` otherwise brightway/AB would be basically unusable without a fast solver on those archs.

**Comment by m-rossi** [comment]
@haasad `scikit-umfpack` is then used instead of `pypardiso` in `bw2calc` on osx-arm?. IMO it should be enough to change the [bw2calc-feedstock](https://github.com/conda-forge/bw2calc-feedstock) to be _not_ `noarch`. Unsupported architectures will simply fail during installation as there is no `bw2calc` package available.

I'm sorry I missed during initial creation of the recipes.

**Comment by haasad** [comment]
I think it should be:
```
run:
...
    - pypardiso  # [not osx-arm64]
    - scikit-umfpack  # [osx-arm64]
...
```
But I have only worked with `noarch` builds lately, so I'm not 100% sure if that's already enough

**Comment by haasad** [comment]
Installation from conda-forge doesn't fully work yet, because no solver library is installed. See https://github.com/conda-forge/bw2calc-feedstock/issues/6

This means that the installation of the AB stable is currently "broken", because even with our old installation instructions `conda-forge` has a higher priority than the `cmutel` channel.

**Comment by m-rossi** [comment]
> Installation from conda-forge doesn't fully work yet, because no solver library is installed. See [conda-forge/bw2calc-feedstock#6](https://github.com/conda-forge/bw2calc-feedstock/issues/6)
> 
> This means that the installation of the AB stable is currently "broken", because even with our old installation instructions `conda-forge` has a higher priority than the `cmutel` channel.

It was resolved in https://github.com/conda-forge/admin-requests/pull/528.

**Comment by Zoophobus** [comment]
Thanks to @m-rossi @haasad for your hard work on this, it's fantastic to be able to use this system. I will close this issue as fixed for now
