### ISSUE TITLE
Help understanding how activity parameters work.

### ISSUE THREAD

**Issue by MaximeAgez** [LCA-ActivityBrowser/activity-browser#934]
Hi,
I have a small project to make an exporter taking a SimaPro CSV and dumping it into activity-browser. There are some hurdles to account for (multi-output processes for example), but right now I am struggling to have the parameters exported AND working. If people have some idea where I am missing something that would help me greatly. 

Of course when the module will ultimately work, I am willing to share it with anyone interested.

After using write_database() and after creating database parameters through write_database_parameters() (both functions from the SimaProCSVImporter class of brightway2), I then define activity parameters using the new_activity_parameters() function of bw2data.parameters. I make sure to have only one group of activity parameters per activity parameters. The import happens properly as can be shown in the parameters.db screenshot below:

![image](https://user-images.githubusercontent.com/24285636/217951548-853d1d21-37f2-4475-af2c-58d5b76d648f.png)

and in AB

![image](https://user-images.githubusercontent.com/24285636/217952073-1233d4dd-f697-4e65-ae0d-37d12217156b.png)

I also made sure to add the _1 unit activity parameters which (to my knowledge) are required for the formulas to work as intended.

The problem that I have is that the values that are shown in AB are not the values calculated from formulas.
I suspect the problem to be that none of the exchanges that are created through the write_database() function are defined as parametrized exchanges within the parameters.db. The problem is that I have no idea how to force brightway to create those parametrized exchanges in the parameters.db. 

Anyone knows?

Thanks!

**Comment by bsteubing** [comment]
Hi Maxime, thanks for raising this issue. I am wondering if this should not be discussed with @cmutel first and implemented properly at the brightway level? The AB in this case is more like a user interface to the data I think. But maybe I am missing somethings.

**Comment by cmutel** [comment]
@MaximeAgez Sorry that the documentation doesn't provide enough info here, we have a [call for help](https://documentation.brightway.dev/en/latest/) in improving it.

Activity, database, and project parameters exist outside the standard Brightway graph-building. So, I think the problem is that you need to tell Brightway that some exchange `amount` values are parameterized, which is *separate* from creating the variables and formulas. I think the method is [`parameters.add_exchanges_to_group`](https://github.com/brightway-lca/brightway2-data/blob/main/bw2data/parameters.py#L1240). See [the tests](https://github.com/brightway-lca/brightway2-data/blob/main/tests/parameters.py#L874) for examples.

In general, I think it would be perhaps make the most sense to format the activity parameter in the way that `bw2io` expects, and then call [`write_database(activate_parameters=True)`](https://github.com/brightway-lca/brightway2-io/blob/758951f1ee154a2a27e2200a754f1b3b8b60c72d/bw2io/importers/base_lci.py#L203), as this will create the activity parameters and groups automatically, and make sure the relevant exchanges are activated as parameterized.

**Comment by MaximeAgez** [comment]
Thanks @cmutel. I tried to apply both suggestions. The parametrized exchanges are now properly created. But the calculated values are still not updating on AB. I will dig a bit further on my side to try to understand why. 

For now I'll close the issue since the parametrized exchanges are create properly and that was my main question.
