### ISSUE TITLE
Change font color in dark mode/allow for different colour setting from system

### ISSUE THREAD

**Issue by jakobsarthur** [LCA-ActivityBrowser/activity-browser#940]
I'm running AB on MAc OSX  13.1 with the system in dark mode. However, the font of the database activities is not legible in this setting. Perhaps it is possible to have the font colours adjust based on the system settings or have the mode of AB not automatically take the system settings/allow for overwrite. 

<img width="1617" alt="Screenshot 2023-02-21 at 13 31 24" src="https://user-images.githubusercontent.com/22193631/220345706-0d6958c1-4c79-47d2-948a-1bd20447ca43.png">

**Comment by Zoophobus** [comment]
Hi jakobsarthur,

I have previously looked at getting a dark mode working for the AB, however it is pretty fiddly work. This is something that needs to be tackled at the CSS level, and while it is really just naming and testing visual parameters, doing this would take quite a bit of time. Something that we are currently spending on other aspects of the AB. 

What I will do is try and stop the AB from taking the system settings, unfortunately it'll clash with your other programs but it's a smaller price to pay

**Comment by Zoophobus** [comment]
Hi Jakobsarthur,

I was wondering if you could check to see what happens when you use the code from the master branch on my fork of the AB. I've tried to fix the AB settings so that you can still use the AB while keeping you system in a dark mode. It does mean that the AB won't follow the trend, but at least it means you can keep your settings.

Here's the location of my fork https://github.com/Zoophobus/activity-browser
Best,
Zoo
