### ISSUE TITLE
Graph explorer only shows content after "Refresh HTML"

### ISSUE THREAD

**Issue by KarinTreyer** [LCA-ActivityBrowser/activity-browser#948]
When I am in an activity, and click on the graph explorer button, the place where the network should be shown stays empty at first. I have to hit the "Refresh HTML" button, or the "Random Activity" button so that something is displayed. 
I am on 2023.2.16 and windows, but this also happens to a student on 2.7.3 and mac.

**Comment by Zoophobus** [comment]
Hi KarinTreyer,

I believe there should be a fix for this coming out tomorrow. The reason I say believe is because I suspect that this is related to a series of other issues around PyQt. If I am right then this fix should be available tomorrow, if not well then there is more at play.

I'll update you when the conda release comes out

**Comment by Zoophobus** [comment]
Hi KarinTreyer,
the new conda release is out if you want to test it. I hope it does fix your issue, if not then just post again and I'll get back to you!

**Comment by KarinTreyer** [comment]
Thanks! Works perfectly with the new update.
