### ISSUE TITLE
Removing parameters and change their values is not possible sometimes

### ISSUE THREAD

**Issue by siwije** [LCA-ActivityBrowser/activity-browser#991]
I don't know what triggers this as it seems to appear randomly. Some parameters are not possible to delete (Fig 1) and with some (or the same) you cannot change the assigned value (Fig 2). I'm using version 2.8.0.

In this particular case, it's just the parameter "Boiling_time" but I have had issues with other parameters as well.

Edit:
The activity parameters cannot be found in their corresponding activities so it seems like they are just included in the list without actually existing.

Fig 1.
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/79800002/396a6115-e108-45a3-a8fd-e1af530212f1)

Fig 2.
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/79800002/bb9f1dc0-d181-4c03-80fb-2a3b4db1ac66)

**Comment by Zoophobus** [comment]
Hi @siwije,

so this is something that has happened in the past and it's due to differences occurring between the databases at the brightway level. The SQL error is basically saying that it cannot find a parameter that it still has a record of, the AB "lost track" of the parameter. A solution can be to remove the parameter group from the SQL database:

https://github.com/LCA-ActivityBrowser/activity-browser/issues/823

Unfortunately, as Marc in the previous issue stated parameters are unstable and might be best avoided

**Comment by siwije** [comment]
Alright @Zoophobus! Thanks for the help!
